### PR TITLE
Renames and adds an additional page

### PR DESCRIPTION
**Pull request by Dysp**
Here's a quiz.

I renamed a file. Which one?
I also added a file... Can you figure out what I did?

Review the code. Write an answer and approve the PR.

### CODE REVIEW

**Review by cortinabryan — APPROVED** [review]
I see what you did there. that makes sense

**Comment by Dysp** [comment]
Yes. Than you. Will you merge it?

**Comment by Dysp** [comment]
Yes. Merge it.

**Comment by Dysp** [comment]
MERGE IT

**Comment by Dysp** [comment]
Yes almost

**Pull request merged**
